const productos = {
  "Congelados": [
    { nombre: "Aguacate pulpa", dias: 2, tipo: "C" },
    { nombre: "Arroz integral", dias: 1, tipo: "C" },
    { nombre: "Base focaccia tomate cherry", dias: 1, tipo: "C" },
    { nombre: "Brownie", dias: 2, tipo: "C" },
    { nombre: "Buñuelos crema", dias: 2, tipo: "C" },
    { nombre: "Buñuelos nata", dias: 2, tipo: "C" },
    { nombre: "Buñuelos trufa", dias: 2, tipo: "C" },
    { nombre: "Buñuelos viento", dias: 2, tipo: "C" },
    { nombre: "Cebolla caramelizada", dias: 20, tipo: "C" },
    { nombre: "Cookie vainilla", dias: 8, tipo: "C" },
    { nombre: "Dot panadero", dias: 3, tipo: "C" },
    { nombre: "Edamame (Mukimame)", dias: 2, tipo: "C" },
    { nombre: "Mango dados", dias: 2, tipo: "C" },
    { nombre: "Muffin blueberry", dias: 2, tipo: "C" },
    { nombre: "Muffin choco sin gluten", dias: 2, tipo: "C" },
    { nombre: "Muffin chocolate con avellana", dias: 2, tipo: "C" },
    { nombre: "Pan espelta rebanado", dias: 2, tipo: "C" },
    { nombre: "Pan molde brioche", dias: 2, tipo: "C" },
    { nombre: "Pan molde wholegrain", dias: 2, tipo: "C" },
    { nombre: "Pasta rigatoni", dias: 1, tipo: "C" },
    { nombre: "Pollo asado deshebrado", dias: 2, tipo: "C" },
    { nombre: "Pop dots blanco", dias: 2, tipo: "C" },
    { nombre: "Pop dots negritos", dias: 2, tipo: "C" },
    { nombre: "Pop dots sucre", dias: 2, tipo: "C" },
    { nombre: "Salmón ahumado", dias: 2, tipo: "C" },
    { nombre: "Tarta de queso", dias: 2, tipo: "C" },
    { nombre: "Tarta mouse chocolate", dias: 2, tipo: "C" },
    { nombre: "Tarta red velvet", dias: 2, tipo: "C" },
    { nombre: "Tarta zanahoria flor", dias: 2, tipo: "C" },
    { nombre: "Tortitas", dias: 2, tipo: "C" },
    { nombre: "Tortilla campera", dias: 2, tipo: "C" },
    { nombre: "Torrija", dias: 3, tipo: "C" },
    { nombre: "Tortilla francesa", dias: 1, tipo: "C" }
  ],

  "Refrigerados": [
    { nombre: "Aguacate", dias: 1, tipo: "R" },
    { nombre: "Atún claro", dias: 2, tipo: "R" },
    { nombre: "Bacon", dias: 5, tipo: "R" },
    { nombre: "Bebida vegetal almendra", dias: 2, tipo: "R" },
    { nombre: "Bebida vegetal avena", dias: 2, tipo: "R" },
    { nombre: "Bebida vegetal soja", dias: 2, tipo: "R" },
    { nombre: "Ensalada campestre", dias: 3, tipo: "R" },
    { nombre: "Espinacas brotes", dias: 2, tipo: "R" },
    { nombre: "Fresón", dias: 1, tipo: "R" },
    { nombre: "Huevo plancha", dias: 2, tipo: "R" },
    { nombre: "Jamón cocido", dias: 3, tipo: "R" },
    { nombre: "Kiwi", dias: 1, tipo: "R" },
    { nombre: "Leche Pasc BOT 1,5L", dias: 2, tipo: "R" },
    { nombre: "Leche sin lactosa", dias: 2, tipo: "R" },
    { nombre: "Manzana", dias: 1, tipo: "R" },
    { nombre: "Mayonesa", dias: 30, tipo: "R" },
    { nombre: "Mayonesa de trufa", dias: 10, tipo: "R" },
    { nombre: "Nata spray", dias: 15, tipo: "R" },
    { nombre: "Paleta ibérica", dias: 14, tipo: "R" },
    { nombre: "Pechuga de pavo", dias: 3, tipo: "R" },
    { nombre: "Pesto", dias: 3, tipo: "R" },
    { nombre: "Queso Brie", dias: 10, tipo: "R" },
    { nombre: "Queso crema", dias: 7, tipo: "R" },
    { nombre: "Queso Edam", dias: 4, tipo: "R" },
    { nombre: "Queso feta", dias: 3, tipo: "R" },
    { nombre: "Queso lascas", dias: 5, tipo: "R" },
    { nombre: "Queso mezcla semicurado", dias: 5, tipo: "R" },
    { nombre: "Queso mozzarella perlas", dias: 4, tipo: "R" },
    { nombre: "Queso mozzarella rallada", dias: 3, tipo: "R" },
    { nombre: "Rúcula", dias: 3, tipo: "R" },
    { nombre: "Salsa César", dias: 4, tipo: "R" },
    { nombre: "Salsa holandesa", dias: 5, tipo: "R" },
    { nombre: "Sobrasada", dias: 2, tipo: "R" },
    { nombre: "Secallona", dias: 4, tipo: "R" },
    { nombre: "Tomate (abierto)", dias: 1, tipo: "R" },
    { nombre: "Tomate seco", dias: 15, tipo: "R" },
    { nombre: "Tomate cherry cortado", dias: 1, tipo: "R" },
    { nombre: "Zumo limón exprimido", dias: 40, tipo: "R" }
  ],

  "Elaborados": [
    { nombre: "Gloria básica", dias: 1, tipo: "E" },
    { nombre: "Gloria chocolate", dias: 1, tipo: "E" },
    { nombre: "Gloria chocolate blanco", dias: 1, tipo: "E" },
    { nombre: "Gloria de pistacho", dias: 1, tipo: "E" },
    { nombre: "Gloria de oreo", dias: 1, tipo: "E" },
    { nombre: "Gloria de lotus", dias: 1, tipo: "E" },
    { nombre: "Gloria de violetas", dias: 1, tipo: "E" },
    { nombre: "Gloria de nocilla", dias: 1, tipo: "E" },
    { nombre: "Sandwich brioche trufado", dias: 1, tipo: "E" },
    { nombre: "Sandwich salmon club", dias: 1, tipo: "E" },
    { nombre: "Sandwich Santagloria club", dias: 1, tipo: "E" },
    { nombre: "Tosta aguacate y cherry", dias: 1, tipo: "E" },
    { nombre: "Tosta aguacate y salmón", dias: 1, tipo: "E" },
    { nombre: "Tosta aguacate y tortilla", dias: 1, tipo: "E" },
    { nombre: "Tosta benedictine", dias: 1, tipo: "E" },
    { nombre: "Tosta paletilla ibérica", dias: 1, tipo: "E" },
    { nombre: "Focaccia bacon y trufa", dias: 1, tipo: "E" },
    { nombre: "Focaccia feta", dias: 1, tipo: "E" },
    { nombre: "Flautín mixto", dias: 1, tipo: "E" },
    { nombre: "Flautín atún", dias: 1, tipo: "E" },
    { nombre: "Flautín queso", dias: 1, tipo: "E" },
    { nombre: "Flautín paletilla ibérica", dias: 1, tipo: "E" },
    { nombre: "Empanadilla pollo curry", dias: 2, tipo: "E" },
    { nombre: "Empanadilla ternera mechada", dias: 2, tipo: "E" },
    { nombre: "Ensalada italiana", dias: 1, tipo: "E" },
    { nombre: "Ensalada pollo", dias: 1, tipo: "E" },
    { nombre: "Ensalada salmón", dias: 1, tipo: "E" },
    { nombre: "Tortitas frutos rojos", dias: 1, tipo: "E" }
  ],

  "Secos": [
    { nombre: "Aceite de oliva virgen 3x5lt", dias: 60, tipo: "S" },
    { nombre: "Almendra granillo", dias: 0, tipo: "S" },
    { nombre: "Avellana tostada", dias: 0, tipo: "S" },
    { nombre: "Azúcar glass saco 10kg", dias: 0, tipo: "S" },
    { nombre: "Azúcar", dias: 0, tipo: "S" },
    { nombre: "Café eco nat descafeinado", dias: 5, tipo: "S" },
    { nombre: "Café eco nat SG 8x1kg", dias: 5, tipo: "S" },
    { nombre: "Canela molida", dias: 0, tipo: "S" },
    { nombre: "Caramelos violetas", dias: 0, tipo: "S" },
    { nombre: "Cebolla frita deshidratada", dias: 15, tipo: "S" },
    { nombre: "Choco crispies", dias: 0, tipo: "S" },
    { nombre: "Cobertura blanca choco 10kg", dias: 0, tipo: "S" },
    { nombre: "Cobertura vegetal choco", dias: 0, tipo: "S" },
    { nombre: "Coco rallado", dias: 0, tipo: "S" },
    { nombre: "Crema pastelera saco", dias: 0, tipo: "S" },
    { nombre: "Crema pistacho", dias: 0, tipo: "S" },
    { nombre: "Frappé vainilla", dias: 0, tipo: "S" },
    { nombre: "Galleta molida lotus", dias: 15, tipo: "S" },
    { nombre: "Galleta molida oreo", dias: 15, tipo: "S" },
    { nombre: "Gelatina miroir cubo", dias: 0, tipo: "S" },
    { nombre: "Glasseado (cinamon roll)", dias: 20, tipo: "S" },
    { nombre: "Granos de chía", dias: 0, tipo: "S" },
    { nombre: "Mermelada frutos bosque", dias: 0, tipo: "S" },
    { nombre: "Miel de flores", dias: 365, tipo: "S" },
    { nombre: "Nocciolata", dias: 0, tipo: "S" },
    { nombre: "Nocilla fluida", dias: 0, tipo: "S" },
    { nombre: "Nueces cuartos", dias: 30, tipo: "S" },
    { nombre: "Orégano seco", dias: 0, tipo: "S" },
    { nombre: "Pipas de calabaza", dias: 0, tipo: "S" },
    { nombre: "Pistacho granillo", dias: 0, tipo: "S" },
    { nombre: "Semilla sésamo", dias: 0, tipo: "S" },
    { nombre: "Sirope lotus", dias: 60, tipo: "S" },
    { nombre: "Sirope violeta", dias: 60, tipo: "S" }
  ]
};

 const obradorData = {
  "productos": [
    {
      "nombre": "Gloria Básica",
      "categoria": "Bollería Dulce",
      "descongelacion": "Hornear desde congelado.",
      "horno_temp": "185°C",
      "horno_prog": "1",
      "horno_tiempo": "15 min",
      "ingredientes_resumen": "Croissant pequeño (1 ud), Almíbar (subreceta)",
      "ingredientes": "Croissant Pequeño Mantequilla (1 ud), Almíbar (30 g)",
      "preparacion": "Hornear el croissant pequeño a 185°C durante 15 min (Prog. 1). Al salir del horno, sumergir completamente en almíbar y escurrir sobre una rejilla."
    },
    {
      "nombre": "Gloria Chocolate",
      "categoria": "Bollería Dulce",
      "descongelacion": "Usar Gloria Básica ya horneada y fría.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Gloria básica (1 ud), Cobertura de chocolate (8 g)",
      "ingredientes": "Gloria Básica (1 ud), Cobertura Vegetal Chocolate (8 g)",
      "preparacion": "Bañar ambas puntas de la gloria en cobertura de chocolate derretida. Dejar cristalizar."
    },
    {
      "nombre": "Gloria Chocolate Blanco",
      "categoria": "Bollería Dulce",
      "descongelacion": "Usar Gloria Básica ya horneada y fría.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Gloria básica (1 ud), Cobertura de chocolate blanco (8 g)",
      "ingredientes": "Gloria Básica (1 ud), Cobertura Blanca (8 g)",
      "preparacion": "Bañar ambas puntas de la gloria con cobertura de chocolate blanco derretido. Dejar cristalizar."
    },
    {
      "nombre": "Supergloria Pistacho",
      "categoria": "Bollería Dulce",
      "descongelacion": "Usar Gloria Básica ya horneada y fría.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Gloria básica (1 ud), Cobertura de Pistacho (subreceta), Pistacho granillo (2 g)",
      "ingredientes": "Gloria Básica (1 ud), Subreceta Cobertura Pistacho (10 g), Pistacho Granillo (2 g)",
      "preparacion": "Bañar las puntas de la gloria con la cobertura de pistacho y rebozar con el granillo de pistacho en fresco."
    },
    {
      "nombre": "Supergloria Lotus",
      "categoria": "Bollería Dulce",
      "descongelacion": "Usar Gloria Básica ya horneada y fría.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Gloria básica (1 ud), Crema lotus (20 g), Galleta molida lotus (2 g)",
      "ingredientes": "Gloria Básica (1 ud), Sirope Lotus (20 g), Galleta Molida Lotus (2 g)",
      "preparacion": "Rellenar la gloria con 15g de sirope de lotus. Bañar las puntas con 5g del mismo sirope y espolvorear galleta molida por encima."
    },
    {
      "nombre": "Supergloria Oreo",
      "categoria": "Bollería Dulce",
      "descongelacion": "Usar Gloria Básica ya horneada y fría.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Gloria básica (1 ud), Nocciolata (20 g), Galleta oreo molida (2 g)",
      "ingredientes": "Gloria Básica (1 ud), Nocciolata (20 g), Galleta Oreo Molida (2 g)",
      "preparacion": "Rellenar la gloria con 15g de Nocciolata. Cubrir las puntas con 5g de Nocciolata y espolvorear la galleta Oreo molida."
    },
    {
      "nombre": "Supergloria Filipinos Blanco",
      "categoria": "Bollería Dulce",
      "descongelacion": "Usar Gloria Básica ya horneada y fría.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Gloria básica (1 ud), Cobertura blanca (10 g), Filipino blanco triturado (4 g)",
      "ingredientes": "Gloria Básica (1 ud), Cobertura Blanca (10 g), Filipino Blanco Triturado (4 g)",
      "preparacion": "Bañar las puntas de la gloria con la cobertura blanca. Repartir los filipinos blancos troceados antes de que solidifique."
    },
    {
      "nombre": "Croissant 100% Mantequilla (Vienes Sophie)",
      "categoria": "Bollería Dulce",
      "descongelacion": "Colocar sin descongelar en bandeja con separación de 5cm y dejar descongelar 20 minutos.",
      "horno_temp": "185°C",
      "horno_prog": "1",
      "horno_tiempo": "15 min (aprox)",
      "ingredientes_resumen": "Croissant Vienes Sophie (1 ud)",
      "ingredientes": "Croissant Vienes Sophie (1 ud)",
      "preparacion": "Colocar los croissants en bandeja con papel siliconado y 5cm de separación. Dejar descongelar 20 minutos. Hornear a 185°C durante 15 minutos (aprox) hasta obtener un color dorado. Exponer sin añadir nada."
    },
    {
      "nombre": "Croissant Chocolate",
      "categoria": "Bollería Dulce",
      "descongelacion": "Colocar sin descongelar en bandeja con separación y descongelar 20 minutos.",
      "horno_temp": "185°C",
      "horno_prog": "1",
      "horno_tiempo": "15 min (aprox)",
      "ingredientes_resumen": "Croissant Paris Choco (1 ud), Cobertura de chocolate (8 g)",
      "ingredientes": "Croissant Paris Choco S/DEC (1 ud), Cobertura Vegetal Choc (8 g)",
      "preparacion": "Descongelar 20 min. Hornear a 185°C por 15 min (Prog. 1) y dejar enfriar. Fundir la cobertura y pintar ambas puntas del croissant. Dejar cristalizar."
    },
    {
      "nombre": "Croissant Curvo Cereales",
      "categoria": "Bollería Dulce",
      "descongelacion": "Hornear directamente desde congelado.",
      "horno_temp": "185°C",
      "horno_prog": "1",
      "horno_tiempo": "15 min (aprox)",
      "ingredientes_resumen": "Croissant Curvo Cereales (1 ud)",
      "ingredientes": "Croissant Curvo Cereales/Tostado (1 ud)",
      "preparacion": "Colocar los croissants sin descongelar sobre papel de horno con separación. Hornear a 185°C durante 15 minutos (aprox). Exponer tal cual."
    },
    {
      "nombre": "Croissant Crema Pistacho y Chocolate",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar croissant durante 20 minutos.",
      "horno_temp": "185°C",
      "horno_prog": "1",
      "horno_tiempo": "15 min (aprox)",
      "ingredientes_resumen": "Croissant (1 ud), Crema de pistacho (30 g), Glaseado (5 g), Pistacho granillo (3 g)",
      "ingredientes": "Croissant Vienes Sophie (1 ud), Choco Cream Pistacho (30 g), Glaseado (subreceta, 5 g), Pistacho Granillo (3 g)",
      "preparacion": "Hornear el croissant (descongelado 20 min) a 185°C por 15 min. Dejar enfriar. Crear un agujero en un extremo. Rellenar con crema de pistacho usando una manga. Decorar con glaseado y esparcir pistacho troceado."
    },
    {
      "nombre": "Croissant Crema Avellanas con Avellana",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar croissant durante 20 minutos.",
      "horno_temp": "185°C",
      "horno_prog": "1",
      "horno_tiempo": "15 min (aprox)",
      "ingredientes_resumen": "Croissant (1 ud), Nocciolata (50 g), Cobertura de chocolate (8 g), Avellana tostada (5 g)",
      "ingredientes": "Croissant Vienes Sophie (1 ud), Nocciolata (50 g), Cobertura Vegetal Choc (8 g), Avellana Tostada (5 g)",
      "preparacion": "Hornear el croissant (descongelado 20 min) a 185°C por 15 min. Dejar enfriar. Crear un agujero en un extremo. Rellenar con Nocciolata. Decorar con líneas de cobertura de chocolate. Colocar dos avellanas enteras en la entrada y el resto troceado encima."
    },
    {
      "nombre": "Flat Croissant Choco Pistacho",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar 30 minutos a temperatura ambiente.",
      "horno_temp": "185°C",
      "horno_prog": "1",
      "horno_tiempo": "18 min",
      "ingredientes_resumen": "Croissant (1 ud), Cobertura de chocolate (15 g), Pistacho granillo (3 g)",
      "ingredientes": "Croissant Selection D'or (1 ud), Cobertura Vegetal Choc (15 g), Pistacho Granillo (3 g)",
      "preparacion": "Descongelar 30 min. Poner papel de horno encima, aplastar con una placa. Hornear en Prog. 1 con la placa encima. Al salir, presionar de nuevo con fuerza. Dejar atemperar. Bañar la mitad con cobertura de chocolate y repartir el pistacho antes de que solidifique."
    },
    {
      "nombre": "Flat Croissant Choco Blanco Lotus",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar 30 minutos a temperatura ambiente.",
      "horno_temp": "185°C",
      "horno_prog": "1",
      "horno_tiempo": "18 min",
      "ingredientes_resumen": "Croissant (1 ud), Cobertura blanca (15 g), Galleta molida Lotus (3 g)",
      "ingredientes": "Croissant Selection D'or (1 ud), Cobertura Blanca (15 g), Galleta Molida Lotus (3 g)",
      "preparacion": "Descongelar 30 min. Poner papel de horno encima, aplastar con una placa. Hornear en Prog. 1 con la placa encima. Al salir, presionar de nuevo con fuerza. Dejar atemperar. Bañar la mitad con cobertura blanca y repartir la galleta lotus antes de que solidifique."
    },
    {
      "nombre": "Roll Canela",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar 90 minutos a temperatura ambiente.",
      "horno_temp": "185°C",
      "horno_prog": "1",
      "horno_tiempo": "16 min",
      "ingredientes_resumen": "Roll Canela (1 ud), Glaseado (20 g)",
      "ingredientes": "Roll Canela (1 ud), Glaseado (subreceta, 20 g)",
      "preparacion": "Descongelar durante 90 minutos a temperatura ambiente. Hornear a 185°C durante 16 minutos. Dejar enfriar y repartir el glaseado por encima."
    },
    {
      "nombre": "Palmera de Mantequilla",
      "categoria": "Bollería Dulce",
      "descongelacion": "Hornear directamente desde congelado.",
      "horno_temp": "170°C",
      "horno_prog": "3",
      "horno_tiempo": "20-25 min",
      "ingredientes_resumen": "Palmera Mantequilla (1 ud)",
      "ingredientes": "Palmera Mantequilla (1 ud)",
      "preparacion": "Hornear directamente desde congelado a 170°C durante 20-25 minutos (Prog. 3) hasta que esté dorada. Exponer."
    },
    {
      "nombre": "Palmera Chocolate Negro",
      "categoria": "Bollería Dulce",
      "descongelacion": "Usar Palmera de Mantequilla ya horneada y fría.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Palmera Mantequilla (1 ud), Cobertura de chocolate (40 g)",
      "ingredientes": "Palmera Mantequilla horneada (1 ud), Cobertura Vegetal Choc (40 g)",
      "preparacion": "Bañar la palmera hasta la mitad con cobertura de chocolate negro derretida. Dejar cristalizar sobre papel de horno."
    },
    {
      "nombre": "Muffin Blueberry",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar a temperatura ambiente.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Muffin Filly Blueberry (1 ud)",
      "ingredientes": "Muffin Filly Blueberry (Arándanos) (1 ud)",
      "preparacion": "Descongelar a temperatura ambiente y exponer."
    },
    {
      "nombre": "Muffin Chocolate con Avellana",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar a temperatura ambiente.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Muffin Choco Nougat (1 ud)",
      "ingredientes": "Muffin Choco Nougat (1 ud)",
      "preparacion": "Descongelar a temperatura ambiente y exponer."
    },
    {
      "nombre": "Muffin Chocolate Sin Gluten",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar a temperatura ambiente.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Muffin Choco Sin Gluten (1 ud)",
      "ingredientes": "Muffin Choco Sin Gluten (1 ud)",
      "preparacion": "Descongelar a temperatura ambiente y exponer."
    },
    {
      "nombre": "Dot Clásico",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar al momento.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Dot Panadero (1 ud)",
      "ingredientes": "Dot Panadero (1 ud)",
      "preparacion": "Descongelar al momento y exponer."
    },
    {
      "nombre": "Dot Chocolate Lotus",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar al momento.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Dot Panadero (1 ud), Cobertura de chocolate (14 g), Galleta molida Lotus (2 g)",
      "ingredientes": "Dot Panadero (1 ud), Cobertura Vegetal Choc (14 g), Galleta Molida Lotus (2 g)",
      "preparacion": "Descongelar el dot. Bañar en cobertura de chocolate derretida y escurrir. Antes de que solidifique, repartir la galleta lotus por encima."
    },
    {
      "nombre": "Dot Chocolate Blanco Filipinos",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar al momento.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Dot Panadero (1 ud), Cobertura blanca (15 g), Filipino blanco triturado (5 g)",
      "ingredientes": "Dot Panadero (1 ud), Cobertura Blanca (15 g), Filipino Blanco Triturado (5 g)",
      "preparacion": "Descongelar el dot. Bañar en cobertura blanca derretida y escurrir. Antes de que solidifique, repartir los filipinos blancos triturados por encima."
    },
    {
      "nombre": "Hole Azúcar",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar 15-20 minutos a temperatura ambiente.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Popdots Sucre (1 ud)",
      "ingredientes": "Popdots Sucre (1 ud)",
      "preparacion": "Descongelar 15-20 minutos a temperatura ambiente y exponer."
    },
    {
      "nombre": "Hole Chocolate Blanco",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar 15-20 minutos a temperatura ambiente.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Popdots Blanco (1 ud)",
      "ingredientes": "Popdots Blanco (1 ud)",
      "preparacion": "Descongelar 15-20 minutos a temperatura ambiente y exponer."
    },
    {
      "nombre": "Hole Chocolate Negro",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar 15-20 minutos a temperatura ambiente.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Popdots Negritos (1 ud)",
      "ingredientes": "Popdots Negritos (1 ud)",
      "preparacion": "Descongelar 15-20 minutos a temperatura ambiente y exponer."
    },
    {
      "nombre": "Bendita Cookie Chocolate y Arroz Inflado",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar 15 minutos a temperatura ambiente.",
      "horno_temp": "170°C",
      "horno_prog": "-",
      "horno_tiempo": "14-16 min",
      "ingredientes_resumen": "Bendita Cookie Choco & Rice (1 ud)",
      "ingredientes": "Bendita Cookie Choco & Rice (1 ud)",
      "preparacion": "Descongelar 15 minutos. Hornear a 170°C durante 14-16 minutos. Dejar enfriar completamente antes de manipular."
    },
    {
      "nombre": "Bendita Cookie Pistacho",
      "categoria": "Bollería Dulce",
      "descongelacion": "Descongelar 15 minutos a temperatura ambiente.",
      "horno_temp": "170°C",
      "horno_prog": "-",
      "horno_tiempo": "14-16 min",
      "ingredientes_resumen": "Bendita Cookie Pistacho (1 ud)",
      "ingredientes": "Bendita Cookie Pistacho (1 ud)",
      "preparacion": "Descongelar 15 minutos. Hornear a 170°C durante 14-16 minutos. Dejar enfriar completamente antes de manipular."
    },
    {
      "nombre": "Crujiente de Manzana",
      "categoria": "Pastelería",
      "descongelacion": "3 minutos a temperatura ambiente.",
      "horno_temp": "170°C",
      "horno_prog": "3",
      "horno_tiempo": "35 min",
      "ingredientes_resumen": "Crujiente Manzana (1 ud), Azúcar (2 g), Gelatina (2 g), Anagrama de chocolate (1 ud)",
      "ingredientes": "Crujiente Manzana Obrador (1 ud), Azúcar (2 g), Gelatina Miroir (2 g), Anagrama Choco Santagloria (1 ud)",
      "preparacion": "Descongelar 3 min. Rebozar la base de hojaldre con azúcar. Hornear a 170°C por 35 minutos (Prog. 3) hasta dorar. Pintar la manzana con gelatina y añadir anagrama."
    },
    {
      "nombre": "Pastel Belem Caprice",
      "categoria": "Pastelería",
      "descongelacion": "Descongelar 45 minutos a temperatura ambiente.",
      "horno_temp": "250°C",
      "horno_prog": "-",
      "horno_tiempo": "8-10 min",
      "ingredientes_resumen": "Pastel de Nata (1 ud), Gelatina (1 g)",
      "ingredientes": "Pastel de Nata Caprice (1 ud), Gelatina Miroir (1 g)",
      "preparacion": "Descongelar el pastel 45 minutos. Cocer 8-10 minutos a 250°C. Desmoldar y pintar con gelatina."
    },
    {
      "nombre": "Brownie",
      "categoria": "Pastelería",
      "descongelacion": "Descongelar a temperatura ambiente.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Brownie (1 ud), Cobertura de chocolate (10 g), Nueces (3 g), Avellanas (4 g), Anagrama de chocolate (1 ud)",
      "ingredientes": "Brownie (1 ud), Cobertura Vegetal Choc (10 g), Nueces Cuartos (1 ud, 3 g), Avellana Tostada (2 uds, 4 g), Anagrama Choco Santagloria (1 ud)",
      "preparacion": "Descongelar el brownie. Bañar la parte superior con cobertura de chocolate caliente. Colocar inmediatamente la nuez y las avellanas partidas. Poner el logo de Santagloria."
    },
    {
      "nombre": "Trenza Danesa",
      "categoria": "Pastelería",
      "descongelacion": "Descongelar 30 minutos a temperatura ambiente.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Trenza Almudevar (1 ud)",
      "ingredientes": "Trenza Almudevar (1 ud)",
      "preparacion": "Descongelar 30 minutos a temperatura ambiente. Cortar en 4 trozos y exponer."
    },
    {
      "nombre": "Tarta de Queso",
      "categoria": "Pastelería",
      "descongelacion": "Descongelar en refrigeración.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Tarta Cremosa de Queso (1 ud), Mermelada Frutos del Bosque (170 g), Anagramas de chocolate (10 uds)",
      "ingredientes": "Tarta Cremosa de Queso (1 ud), Mermelada Frutos del Bosque (170 g), Anagrama Choco Santagloria (10 uds)",
      "preparacion": "Descongelar la tarta en refrigeración. Marcar y cortar 10 porciones. Cubrir con mermelada y colocar un anagrama en cada porción."
    },
    {
      "nombre": "Tarta Mouse Chocolate",
      "categoria": "Pastelería",
      "descongelacion": "Descongelar en refrigeración.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Tarta Mouse Chocolate (1 ud)",
      "ingredientes": "Tarta Mouse Chocolate 12P (1 ud)",
      "preparacion": "Descongelar en refrigeración. Se pueden sacar por porciones y decorar."
    },
    {
      "nombre": "Tarta Flor Zanahoria",
      "categoria": "Pastelería",
      "descongelacion": "Cortar congelada.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Tarta Zanahoria Flor (1 ud)",
      "ingredientes": "Tarta Zanahoria Flor (1 ud), Anagrama Choco Santagloria (10 uds)",
      "preparacion": "Exponer la tarta entera con un anagrama en el centro. Para porciones, cortar la tarta aún congelada en 10 porciones y exponerlas con su anagrama."
    },
    {
      "nombre": "Banda de Hojaldre con Frutas",
      "categoria": "Pastelería",
      "descongelacion": "Placa de hojaldre descongelada.",
      "horno_temp": "170°C",
      "horno_prog": "3",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Placa Hojaldre (200g), Crema Pastelera (245g), Frutas frescas variadas, Gelatina (40g)",
      "ingredientes": "Placa Hojaldre Mantequilla (1/5 de placa), Crema Pastelera (subreceta, 245 g), Manzana Golden (130 g), Kiwi (53 g), Fresón (63 g), Frambuesa (25 g), Moras (31 g), Arándanos (21 g), Gelatina Miroir (40 g), Anagrama Choco Santagloria (1 ud)",
      "preparacion": "Pinchar 1/5 de placa de hojaldre. Colocar crema pastelera en la base. Repartir manzana en una mitad y hornear (Prog. 3). Añadir el resto de crema. Colocar kiwi y fresones. Pintar con gelatina. Distribuir frutos rojos y anagrama. Cortar en 4 trozos."
    },
    {
      "nombre": "Tortitas Frutos Rojos",
      "categoria": "Postres",
      "descongelacion": "Descongelar 1h a temperatura ambiente o el día anterior en frigorífico.",
      "horno_temp": "Merrychef / Horno",
      "horno_prog": "Croissant (Merrychef) / 7 (Horno)",
      "horno_tiempo": "25 seg (Merrychef) / 2 min (Horno a 200°C)",
      "ingredientes_resumen": "Pancakes (3 ud), Mermelada frutos del bosque (60 g), Frutos rojos frescos (30 g), Nata montada (35 g)",
      "ingredientes": "Pancake Americano (3 uds), Mermelada Frutos del Bosque (60 g), Frambuesa (10 g), Arándanos (8 g), Fresón (12 g), Nata Spray (35 g)",
      "preparacion": "Calentar las tortitas. Apilar las 3 tortitas intercalando y cubriendo con mermelada en zigzag. Repartir los frutos rojos por encima. Añadir la nata montada a un lado."
    },
    {
      "nombre": "Tortitas Chocoavellana",
      "categoria": "Postres",
      "descongelacion": "Descongelar 1h a temperatura ambiente o el día anterior en frigorífico.",
      "horno_temp": "Merrychef / Horno",
      "horno_prog": "Croissant (Merrychef) / 7 (Horno)",
      "horno_tiempo": "25 seg (Merrychef) / 2 min (Horno a 200°C)",
      "ingredientes_resumen": "Pancakes (3 ud), Nocciolata (54 g), Filipino blanco triturado (6 g), Nata montada (35 g)",
      "ingredientes": "Pancake Americano (3 uds), Nocciolata (54 g), Filipino Blanco Triturado (6 g), Nata Spray (35 g)",
      "preparacion": "Calentar las tortitas. Apilar las 3 tortitas intercalando y cubriendo con Nocciolata en zigzag. Espolvorear los filipinos troceados. Añadir la nata montada a un lado."
    },
    {
      "nombre": "Bocadillo Mixto",
      "categoria": "Salado",
      "descongelacion": "Usar pan 'Media Santagloria' ya cocido.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Media Santagloria (1 ud), Queso mezcla (54 g), Jamón cocido (40 g)",
      "ingredientes": "Media Santagloria (Bello Cocido) (1 ud), Queso Mezcla Semicurado (54 g, 3 lonchas), Jamón Cocido (40 g, 2 lonchas)",
      "preparacion": "Abrir el pan y colocar 3 lonchas de queso (partidas a la mitad). Poner encima 2 lonchas de jamón york (partidas a la mitad). Cerrar."
    },
    {
      "nombre": "Bocadillo Ibérico",
      "categoria": "Salado",
      "descongelacion": "Usar pan 'Media Santagloria' ya cocido.",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Media Santagloria (1 ud), Tomate triturado (25 g), Paleta Ibérica (35 g)",
      "ingredientes": "Media Santagloria (Bello Cocido) (1 ud), Tomate Pera (Triturado) (25 g), Paleta Ibérica Cebo (35 g)",
      "preparacion": "Abrir el pan a la mitad. Untar tomate en una cara. Colocar las lonchas de paletilla con ondulación. Cerrar."
    },
    {
      "nombre": "Bocadillo Tortilla",
      "categoria": "Salado",
      "descongelacion": "Descongelar tortilla 24h en refrigeración. Usar pan ya cocido.",
      "horno_temp": "180°C (para la tortilla)",
      "horno_prog": "-",
      "horno_tiempo": "20 min (para la tortilla)",
      "ingredientes_resumen": "Media Santagloria (1 ud), Tomate triturado (25 g), Tortilla Campera (1/6 ud)",
      "ingredientes": "Media Santagloria (Bello Cocido) (1 ud), Tomate Pera (Triturado) (25 g), Tortilla Campera (1/6 ud)",
      "preparacion": "Hornear la tortilla descongelada a 180°C por 20 min. Untar la base del pan con tomate. Colocar 1/6 de tortilla (partida en 2 cuñas). Cerrar."
    },
    {
      "nombre": "Bocadillo Vegetal Omega 3",
      "categoria": "Salado",
      "descongelacion": "Descongelar pan 15-20 min a temp. ambiente.",
      "horno_temp": "180°C - 190°C (para el pan)",
      "horno_prog": "-",
      "horno_tiempo": "12 min (para el pan)",
      "ingredientes_resumen": "Pan Omega 3 (1 ud), Mayonesa (20 ml), Ensalada (15 g), Tomate (35 g), Aguacate (35 g), Sal (0.5 g), Atún (70 g)",
      "ingredientes": "PAN OMEGA 3 (1 ud), MAYONESA (20 ml), ENSALADA CAMPESTRE (15 g), TOMATE PERA (35 g), AGUACATE HASS (35 g), SAL FINA (0.5 g), ATUN CLARO AC. GIRASOL (70 g)",
      "preparacion": "Hornear el pan Omega 3 (descongelado 15-20 min) a 180-190°C por 12 min. Abrir lateralmente. Untar la base con mayonesa y añadir la ensalada. Añadir rodajas de tomate y láminas de aguacate. Añadir sal sobre el aguacate. Repartir el atún desmigado. Cerrar. No se recomienda calentar."
    },
    {
      "nombre": "Bocadillo Pollo César",
      "categoria": "Salado",
      "descongelacion": "Descongelar barra 30-40min.",
      "horno_temp": "200°C (pan) / Merrychef (final)",
      "horno_prog": "-",
      "horno_tiempo": "1 min (pan)",
      "ingredientes_resumen": "Media Santagloria (1 ud), Pollo asado (50 g), Cebolla caramelizada (14 g), Espinaca (4 g), Rúcula (4 g), Tomate (50 g), Grana Padano (8 g), Salsa César (30 g)",
      "ingredientes": "Media Santagloria (Bello Cocido) (1 ud), Pollo Asado Deshebrado (50 g), Cebolla Caramelizada (14 g), Brotes Espinaca (4 g), Ensalada Rucula (4 g), Tomate Pera (50 g), Lascas Grana Padano (8 g), Salsa Cesar (30 g)",
      "preparacion": "Hornear la barra (descongelada 30-40min) 1 min a 200°C. Abrir. Repartir pollo, cebolla, espinaca y rúcula. Colocar rodajas de tomate y lascas de Grana Padano. Cerrar. Al pedir, añadir salsa César y calentar en Merrychef o parrilla."
    },
    {
      "nombre": "Bocadillo Ibérico y Brie",
      "categoria": "Salado",
      "descongelacion": "Descongelar barra 30-40min.",
      "horno_temp": "200°C (para el pan)",
      "horno_prog": "-",
      "horno_tiempo": "1 min (para el pan)",
      "ingredientes_resumen": "Media Santagloria (1 ud), Queso Brie (30 g), Paleta Ibérica (35 g)",
      "ingredientes": "Media Santagloria (Bello Cocido) (1 ud), Brie Baguette Cantorel (30 g), Paleta Ibérica Cebo (35 g)",
      "preparacion": "Hornear la barra (descongelada 30-40min) 1 min a 200°C. Abrir. Colocar dos lonchas de brie en la base. Poner la paleta ibérica encima. Cerrar."
    },
    {
      "nombre": "Delicia Integral Hummus y Feta",
      "categoria": "Salado",
      "descongelacion": "Usar hogaza 'Whole Grain' ya horneada y cortada.",
      "horno_temp": "Horno / Tostador",
      "horno_prog": "-",
      "horno_tiempo": "Tostar",
      "ingredientes_resumen": "Hogaza Wholegrain (2 rebanadas), Hummus (30 g), Queso Feta (10 g), Tomate (25 g), Rúcula (4 g), Sésamo (0.5 g), AOVE (3 ml)",
      "ingredientes": "Hogaza Wholegrain (2 rebanadas), Hummus de pimentón (30 g), Queso Feta Dados (10 g), Tomate Pera (25 g), Rúcula (4 g), Semillas Sésamo Blanco (0,5 g), AOVE (3 ml)",
      "preparacion": "Tostar las rebanadas. Poner hummus en la base y repartir feta desmigado. Colocar dos rodajas de tomate y rúcula. Repartir AOVE y sésamo. Cerrar."
    },
    {
      "nombre": "Delicia Integral Mortadela Italiana",
      "categoria": "Salado",
      "descongelacion": "Usar hogaza 'Whole Grain' ya horneada y cortada.",
      "horno_temp": "Horno / Tostador",
      "horno_prog": "-",
      "horno_tiempo": "Tostar",
      "ingredientes_resumen": "Hogaza Wholegrain (2 rebanadas), Mayonesa (10 ml), Queso Edam (20 g), Mortadela (20 g), Espinaca (3 g), Cebolla caramelizada (6 g), Tomate seco (2 g)",
      "ingredientes": "Hogaza Wholegrain (2 rebanadas), Mayonesa (10 ml), Queso Edam (1 loncha), Mortadela Bologna (1 loncha), Brotes Espinaca (3 g), Cebolla Caramelizada (6 g), Pomodori Secchi (2 g)",
      "preparacion": "Tostar las rebanadas. Untar mayonesa en la base y colocar el queso. Doblar la mortadela y colocar. Poner espinaca, cebolla caramelizada y tomate seco en juliana. Cerrar."
    },
    {
      "nombre": "Bikini Clásico",
      "categoria": "Salado",
      "descongelacion": "Pan de molde descongelado.",
      "horno_temp": "Merrychef",
      "horno_prog": "SW/MIXTO",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Pan Brioche (2 rebanadas), Queso Edam (2 lonchas), Jamón Cocido (1.5 lonchas)",
      "ingredientes": "PAN MOLDE BRIOCHE (2 rebanadas), QUESO EDAM (2 lonchas), JAMÓN COCIDO (1.5 lonchas)",
      "preparacion": "Tostar el pan brioche hasta dorar. Poner una loncha de queso, luego el jamón y encima la otra loncha de queso. Tapar, empapelar y exponer. Regenerar al momento en programa SW/MIXTO."
    },
    {
      "nombre": "Bikini Sobrasada",
      "categoria": "Salado",
      "descongelacion": "Pan de molde descongelado.",
      "horno_temp": "Merrychef",
      "horno_prog": "SW/MIXTO",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Pan Brioche (2 rebanadas), Sobrasada (20 g), Queso mezcla (20 g), Queso Brie (40 g)",
      "ingredientes": "PAN MOLDE BRIOCHE (2 rebanadas), SOBRASADA (20 g), QUESO MEZCLA SEMICURADO (20 g), QUESO BRIE (40 g)",
      "preparacion": "Tostar el pan brioche hasta dorar. Poner la loncha de queso mezcla y extender la sobrasada encima. Cubrir con el queso brie, tapar, empapelar y exponer. Regenerar al momento en programa SW/MIXTO."
    },
    {
      "nombre": "Croissant Ibérico y Brie",
      "categoria": "Salado",
      "descongelacion": "Descongelar croissant durante 20 minutos.",
      "horno_temp": "180°C",
      "horno_prog": "1",
      "horno_tiempo": "15 min (aprox)",
      "ingredientes_resumen": "Croissant (1 ud), Paleta Ibérica (30 g), Queso Brie (20 g)",
      "ingredientes": "Croissant Vienes Sophie (1 ud), Paleta Ibérica Cebo (30 g), Brie Baguette Cantorel (20 g)",
      "preparacion": "Hornear el croissant (descongelado 20 min) a 180°C por 15 min. Abrir desde los cuernos. Añadir el jamón ibérico con volumen y dos lonchas de brie. Cerrar."
    },
    {
      "nombre": "Croissant Mixto",
      "categoria": "Salado",
      "descongelacion": "Descongelar croissant durante 20 minutos.",
      "horno_temp": "180°C",
      "horno_prog": "1",
      "horno_tiempo": "15 min (aprox)",
      "ingredientes_resumen": "Croissant (1 ud), Queso mezcla (40 g), Jamón cocido (20 g)",
      "ingredientes": "Croissant Vienes Sophie (1 ud), Queso Mezcla Semicurado (2 lonchas), Jamón Cocido (2 lonchas)",
      "preparacion": "Hornear el croissant (descongelado 20 min) a 180°C por 15 min. Abrir. Cortar las lonchas de queso por la mitad y repartir. Cortar las lonchas de jamón por la mitad y repartir encima. Cerrar."
    },
    {
      "nombre": "Focaccia Bacon Brie & Trufa",
      "categoria": "Salado",
      "descongelacion": "Base de focaccia descongelada.",
      "horno_temp": "Merrychef",
      "horno_prog": "2 (Focaccias)",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Base Focaccia (0,5 ud), Mozzarella (240 g), Bacon (272 g), Brie (160 g), Mayonesa trufada (80 g), Tomate seco (56 g)",
      "ingredientes": "Base Focaccia Tomate Cherry (0,5 ud), Mozzarella Rallada (240 g), Bacon Troceado (272 g), Brie Baguette (160 g), Mayonesa Trufa (80 g), Pomodori Secchi (56 g)",
      "preparacion": "Sobre media base de focaccia, distribuir mozzarella, bacon y brie (2 mitades/porción). Hornear (Prog. 2). Cortar en 8 porciones. Una vez tibio, añadir mayonesa trufada en zig-zag y tomate seco en juliana."
    },
    {
      "nombre": "Focaccia Feta Cebolla Caramelizada & Pistacho",
      "categoria": "Salado",
      "descongelacion": "Base de focaccia descongelada.",
      "horno_temp": "Merrychef",
      "horno_prog": "2 (Focaccias)",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Base Focaccia (0,5 ud), Mozzarella (240 g), Cebolla caramelizada (180 g), Queso Feta (95 g), Tomate seco (56 g), Pistacho granillo (12 g), Orégano (3 g)",
      "ingredientes": "Base Focaccia Tomate Cherry (0,5 ud), Mozzarella Rallada (240 g), Cebolla Caramelizada (180 g), Queso Feta Dados (95 g), Pomodori Secchi (56 g), Pistacho Granillo (12 g), Orégano Seco (3 g)",
      "preparacion": "Sobre media base de focaccia, distribuir mozzarella y cebolla. Hornear (Prog. 2). Una vez tibio, repartir feta desmigado, tomate seco en juliana, pistacho y orégano. Cortar en 8 porciones."
    },
    {
      "nombre": "Focaccia Bacon y Mozzarella",
      "categoria": "Salado",
      "descongelacion": "Base de focaccia descongelada.",
      "horno_temp": "180°C",
      "horno_prog": "-",
      "horno_tiempo": "5 min",
      "ingredientes_resumen": "Base Focaccia (0,5 ud), Mozzarella (300 g), Bacon (100 g), AOVE (2 ml), Orégano (1 g)",
      "ingredientes": "Base Focaccia Tomate Cherry (0,5 ud), Mozzarella Rallada (300 g), Bacon Troceado (100 g), AOVE (2 ml), Orégano Seco (1 g)",
      "preparacion": "Sobre media base de focaccia, distribuir la mozzarella y el bacon. Hornear a 180°C por 5 min con 20% de humedad. Cortar en 8 porciones y aderezar con AOVE y orégano."
    },
    {
      "nombre": "Focaccia Queso de Cabra y Cebolla Caramelizada",
      "categoria": "Salado",
      "descongelacion": "Base de focaccia descongelada.",
      "horno_temp": "180°C",
      "horno_prog": "-",
      "horno_tiempo": "5 min",
      "ingredientes_resumen": "Base Focaccia (0,5 ud), Mozzarella (200 g), Cebolla caramelizada (200 g), Rulo de cabra (250 g)",
      "ingredientes": "Base Focaccia Tomate Cherry (0,5 ud), Mozzarella Rallada (200 g), Cebolla Caramelizada (200 g), Rulo Queso Cabra (250 g)",
      "preparacion": "Sobre media base de focaccia, añadir mozzarella y cebolla caramelizada. Cortar el rulo de cabra en rodajas finas, partirlas a la mitad y colocar sobre la base. Hornear a 180°C por 5 min con 20% de humedad. Cortar en 8 porciones."
    },
    {
      "nombre": "Ensalada de Salmón",
      "categoria": "Ensaladas",
      "descongelacion": "-",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Ensalada campestre (30 g), Espinaca (40 g), Arroz integral (80 g), Mango (50 g), Salmón ahumado (30 g), Nueces (15 g), Tomate cherry (40 g), Hierbabuena (2 g)",
      "ingredientes": "Ensalada Campestre (30 g), Brotes Espinaca (40 g), Arroz Integral (80 g), Mango (50 g), Salmón Ahumado (30 g), Nueces (15 g), Tomate Cherry (4 uds), Micromezclum (3 g), Hierbabuena (2 g)",
      "preparacion": "En un bowl, poner espinacas y ensalada. Colocar arroz, mango en dados, salmón en tiras, nueces y tomates cherry en mitades. Poner micro mézclum en el centro y hierbabuena en juliana sobre el mango. Se recomienda vinagreta oriental."
    },
    {
      "nombre": "Ensalada de Pollo",
      "categoria": "Ensaladas",
      "descongelacion": "-",
      "horno_temp": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Ensalada campestre (50 g), Espinaca (20 g), Edamame (40 g), Pollo asado (50 g), Queso Feta (30 g), Nueces (15 g), Tomate cherry (40 g), Fresón (30 g), Hierbabuena (2 g)",
      "ingredientes": "Ensalada Campestre (50 g), Brotes Espinaca (20 g), Tomate Cherry (4 uds), Fresón (30 g), Mukimame (Edamame, 40 g), Pollo Asado Desmigado (50 g), Queso Feta (30 g), Nueces (15 g), Hierbabuena (2 g)",
      "preparacion": "En un bowl, poner ensalada y espinacas. Colocar cherrys, fresones, edamame, pollo, feta y nueces. Terminar con hierbabuena en juliana. Se recomienda vinagreta oriental."
    },
    {
      "nombre": "Ensalada Italiana",
      "categoria": "Ensaladas",
      "descongelacion": "-",
      "horno_temp": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Espinaca (15 g), Rúcula (5 g), Pasta Rigatoni (160 g), Atún (70 g), Tomate seco (10 g), Grana Padano (10 g), Mozzarella fresca (30 g), Tomate cherry (40 g)",
      "ingredientes": "Brotes Espinaca (15 g), Rúcula (5 g), Pasta Rigatoni cocida (160 g), AOVE (10 ml), Atún Claro (70 g), Pomodori Secchi (10 g), Lascas Grana Padano (10 g), Mozzarella Fresca Minibol (30 g), Tomate Cherry (4 uds)",
      "preparacion": "En un bowl, repartir espinaca y rúcula. En la otra mitad, la pasta con AOVE. Colocar atún, tomates cherry, tomate seco, lascas de grana padano y perlas de mozzarella. Se recomienda vinagreta de pesto."
    },
    {
      "nombre": "Subreceta Crema Pastelera",
      "categoria": "Subreceta",
      "descongelacion": "-",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Leche (1500 ml), Preparado para Crema Pastelera (500 g)",
      "ingredientes": "Leche Entera (1500 ml), Crema Pastelera en polvo (500 g)",
      "preparacion": "Batir la leche y añadir la crema en polvo en dos partes, batiendo continuamente hasta obtener una textura uniforme. Si hay grumos, triturar. Poner en manga pastelera. Caducidad: 24h en refrigeración."
    },
    {
      "nombre": "Subreceta Almíbar",
      "categoria": "Subreceta",
      "descongelacion": "-",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Agua (1000 ml), Azúcar (1000 g), Miel (400 g)",
      "ingredientes": "Agua (1000 ml), Azúcar (1000 g), Miel de Flores (400 g)",
      "preparacion": "Mezclar todos los ingredientes en un cazo y llevar a ebullición. Caducidad: 4 días."
    },
    {
      "nombre": "Subreceta Glaseado",
      "categoria": "Subreceta",
      "descongelacion": "-",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Preparado Glaseado (500 g), Agua (500 ml)",
      "ingredientes": "Preparado para Glaseado (500 g), Agua (500 ml)",
      "preparacion": "Mezclar el preparado con el agua. Caducidad: 10 días."
    },
    {
      "nombre": "Subreceta Cobertura Pistacho",
      "categoria": "Subreceta",
      "descongelacion": "-",
      "horno_temp": "-",
      "horno_prog": "-",
      "horno_tiempo": "-",
      "ingredientes_resumen": "Cobertura blanca (100 g), Crema de pistacho (40 g)",
      "ingredientes": "Cobertura Blanca (100 g), Crema de Pistacho (40 g)",
      "preparacion": "Fundir la cobertura blanca y mezclar con la crema de pistacho. Caducidad: 1 día."
    }
  ]
 };


