const productos = {
  "Congelados": [
    { nombre: "Aguacate pulpa", dias: 2, tipo: "C" },
    { nombre: "Arroz integral", dias: 1, tipo: "C" },
    { nombre: "Base focaccia tomate cherry", dias: 1, tipo: "C" },
    { nombre: "Brownie", dias: 2, tipo: "C" },
    { nombre: "Buñuelos crema", dias: 2, tipo: "C" },
    { nombre: "Buñuelos nata", dias: 2, tipo: "C" },
    { nombre: "Buñuelos trufa", dias: 2, tipo: "C" },
    { nombre: "Buñuelos viento", dias: 2, tipo: "C" },
    { nombre: "Cebolla caramelizada", dias: 20, tipo: "C" },
    { nombre: "Cookie chocolate blanco", dias: 3, tipo: "C" },
    { nombre: "Cookie chocolate con leche", dias: 3, tipo: "C" },
    { nombre: "Cookie avena y pasas", dias: 3, tipo: "C" },
    { nombre: "Dot panadero", dias: 3, tipo: "C" },
    { nombre: "Edamame (Mukimame)", dias: 2, tipo: "C" },
    { nombre: "Mango dados", dias: 2, tipo: "C" },
    { nombre: "Muffin blueberry", dias: 2, tipo: "C" },
    { nombre: "Muffin choco sin gluten", dias: 2, tipo: "C" },
    { nombre: "Muffin chocolate con avellana", dias: 2, tipo: "C" },
    { nombre: "Pan espelta rebanado", dias: 2, tipo: "C" },
    { nombre: "Pan molde brioche", dias: 2, tipo: "C" },
    { nombre: "Pan molde wholegrain", dias: 2, tipo: "C" },
    { nombre: "Pasta rigatoni", dias: 1, tipo: "C" },
    { nombre: "Pollo asado deshebrado", dias: 2, tipo: "C" },
    { nombre: "Pop dots blanco", dias: 2, tipo: "C" },
    { nombre: "Pop dots negritos", dias: 2, tipo: "C" },
    { nombre: "Pop dots sucre", dias: 2, tipo: "C" },
    { nombre: "Salmón ahumado", dias: 2, tipo: "C" },
    { nombre: "Tarta de chocolate fondant", dias: 2, tipo: "C" },
    { nombre: "Tarta de manzana", dias: 2, tipo: "C" },
    { nombre: "Tarta de queso con lotus", dias: 2, tipo: "C" },
    { nombre: "Tarta red velvet", dias: 2, tipo: "C" },
    { nombre: "Tarta zanahoria", dias: 2, tipo: "C" },
    { nombre: "Tortitas", dias: 2, tipo: "C" },
    { nombre: "Tortilla campera", dias: 2, tipo: "C" },
    { nombre: "Torrija", dias: 3, tipo: "C" },
    { nombre: "Tortilla francesa", dias: 1, tipo: "C" }
  ],

  "Refrigerados": [
    { nombre: "Aguacate", dias: 1, tipo: "R" },
    { nombre: "Atún claro", dias: 2, tipo: "R" },
    { nombre: "Bacon", dias: 5, tipo: "R" },
    { nombre: "Bebida vegetal almendra", dias: 2, tipo: "R" },
    { nombre: "Bebida vegetal avena", dias: 2, tipo: "R" },
    { nombre: "Bebida vegetal soja", dias: 2, tipo: "R" },
    { nombre: "Ensalada campestre", dias: 1, tipo: "R" },
    { nombre: "Espinacas brotes", dias: 1, tipo: "R" },
    { nombre: "Fresón", dias: 1, tipo: "R" },
    { nombre: "Huevo plancha", dias: 2, tipo: "R" },
    { nombre: "Jamón cocido", dias: 3, tipo: "R" },
    { nombre: "Kiwi", dias: 1, tipo: "R" },
    { nombre: "Leche Pasc BOT 1,5L", dias: 2, tipo: "R" },
    { nombre: "Leche sin lactosa", dias: 2, tipo: "R" },
    { nombre: "Manzana", dias: 1, tipo: "R" },
    { nombre: "Mayonesa", dias: 30, tipo: "R" },
    { nombre: "Mayonesa de trufa", dias: 10, tipo: "R" },
    { nombre: "Nata spray", dias: 15, tipo: "R" },
    { nombre: "Paleta ibérica", dias: 14, tipo: "R" },
    { nombre: "Pechuga de pavo", dias: 3, tipo: "R" },
    { nombre: "Pesto", dias: 5, tipo: "R" },
    { nombre: "Queso Brie", dias: 10, tipo: "R" },
    { nombre: "Queso crema", dias: 7, tipo: "R" },
    { nombre: "Queso Edam", dias: 4, tipo: "R" },
    { nombre: "Queso feta", dias: 3, tipo: "R" },
    { nombre: "Queso lascas", dias: 5, tipo: "R" },
    { nombre: "Queso mezcla semicurado", dias: 5, tipo: "R" },
    { nombre: "Queso mozzarella perlas", dias: 4, tipo: "R" },
    { nombre: "Queso mozzarella rallada", dias: 3, tipo: "R" },
    { nombre: "Rúcula", dias: 1, tipo: "R" },
    { nombre: "Salsa César", dias: 4, tipo: "R" },
    { nombre: "Salsa holandesa", dias: 5, tipo: "R" },
    { nombre: "Sobrasada", dias: 2, tipo: "R" },
    { nombre: "Secallona", dias: 4, tipo: "R" },
    { nombre: "Tomate (abierto)", dias: 1, tipo: "R" },
    { nombre: "Tomate seco", dias: 15, tipo: "R" },
    { nombre: "Tomate cherry cortado", dias: 1, tipo: "R" },
    { nombre: "Zumo limón exprimido", dias: 40, tipo: "R" },
    { nombre: "Matcha biberón", dias: 3, tipo: "R" },
    { nombre: "Salmón tupper", dias: 3, tipo: "R" }
  ],

  "Elaborados": [
    { nombre: "Almíbar", dias: 4 },
    { nombre: "Almíbar miel", dias: 4 },
    { nombre: "Bacon cocinado", dias: 2 },
    { nombre: "Banda hojaldre frutas", dias: 1 },
    { nombre: "Bocadillo ibérico", dias: 1 },
    { nombre: "Bocadillo ibérico y brie", dias: 1 },
    { nombre: "Bocadillo mixto", dias: 1 },
    { nombre: "Bocadillo pollo César", dias: 1 },
    { nombre: "Bocadillo secallona", dias: 1 },
    { nombre: "Bocadillo tortilla de patata", dias: 1 },
    { nombre: "Bocadillo vegetal omega 3", dias: 1 },
    { nombre: "Bretzel crema y almendra", dias: 2 },
    { nombre: "Chocolate taza (preparado)", dias: 2 },
    { nombre: "Churros", dias: 1 },
    { nombre: "Chusco espelta", dias: 1 },
    { nombre: "Cobertura blanca choco derretida", dias: 3 },
    { nombre: "Cobertura de pistacho", dias: 1 },
    { nombre: "Cobertura vegetal choco derretida", dias: 3 },
    { nombre: "Coca de llardons", dias: 2 },
    { nombre: "Corazón hojaldre fruta y manzana", dias: 1 },
    { nombre: "Corazón hojaldre manzana", dias: 1 },
    { nombre: "Crema pastelera hecha", dias: 1 },
    { nombre: "Croissant crema de pistacho y chocolate", dias: 1 },
    { nombre: "Croissant curvo cereales", dias: 1 },
    { nombre: "Croissant ibérico brie", dias: 1 },
    { nombre: "Croissant mixto", dias: 1 },
    { nombre: "Croissant nocciolata", dias: 1 },
    { nombre: "Croissant Paris choco", dias: 1 },
    { nombre: "Croissant pequeño mantequilla", dias: 1 },
    { nombre: "Croissant vienes Sophie", dias: 1 },
    { nombre: "Crujiente manzana obrador", dias: 1 },
    { nombre: "Dot chocolate blanco y filipinos", dias: 1 },
    { nombre: "Dot chocolate y lotus", dias: 1 },
    { nombre: "Empanadilla pollo curry", dias: 2 },
    { nombre: "Empanadilla ternera mechada", dias: 2 },
    { nombre: "Ensaïmada", dias: 1 },
    { nombre: "Ensalada de pollo", dias: 1 },
    { nombre: "Ensalada de salmón", dias: 1 },
    { nombre: "Ensalada italiana", dias: 1 },
    { nombre: "Flat croissant", dias: 1 },
    { nombre: "Flat croissant choco blanco y lotus", dias: 1 },
    { nombre: "Flat croissant choco pistacho", dias: 1 },
    { nombre: "Flauta ibérica", dias: 1 },
    { nombre: "Flautín atún", dias: 1 },
    { nombre: "Flautín ibérico", dias: 1 },
    { nombre: "Flautín mixto", dias: 1 },
    { nombre: "Flautín queso", dias: 1 },
    { nombre: "Focaccia bacon y trufa", dias: 1 },
    { nombre: "Focaccia feta", dias: 1 },
    { nombre: "Glasseado", dias: 10 },
    { nombre: "Gloria aguacate y pavo", dias: 1 },
    { nombre: "Gloria básica", dias: 1 },
    { nombre: "Gloria chocolate blanco", dias: 1 },
    { nombre: "Gloria de filipinos blancos", dias: 1 },
    { nombre: "Gloria de lotus", dias: 1 },
    { nombre: "Gloria de nocilla", dias: 1 },
    { nombre: "Gloria de oreo", dias: 1 },
    { nombre: "Gloria de pistacho", dias: 1 },
    { nombre: "Gloria de violetas", dias: 1 },
    { nombre: "Gloria jamón ibérico y tomate", dias: 1 },
    { nombre: "Gloria salmón", dias: 1 },
    { nombre: "Limón rodajas", dias: 1 },
    { nombre: "Limonada", dias: 3 },
    { nombre: "Manga de crema de pistacho", dias: 3 },
    { nombre: "Manga de nocciolata", dias: 3 },
    { nombre: "Napolitana bombón fácil", dias: 1 },
    { nombre: "Naranja rodajas", dias: 1 },
    { nombre: "Palmerita petit cereales", dias: 2 },
    { nombre: "Palmerón chocolate", dias: 2 },
    { nombre: "Palmerón mantequilla", dias: 2 },
    { nombre: "Pan baguette GR cereales", dias: 1 },
    { nombre: "Pan baguette GR salvado", dias: 1 },
    { nombre: "Pan baguette gran reserva", dias: 1 },
    { nombre: "Pan cristalino XL", dias: 1 },
    { nombre: "Pan de payés 500g", dias: 1 },
    { nombre: "Pan flautín de aceitunas", dias: 1 },
    { nombre: "Pan flautín semillas", dias: 1 },
    { nombre: "Pan flautín tradición", dias: 1 },
    { nombre: "Pan hogaza avena y semillas", dias: 1 },
    { nombre: "Pan hogaza espelta y sésamo", dias: 1 },
    { nombre: "Pan hogaza sarraceno bio", dias: 1 },
    { nombre: "Pan hogaza wholegrain", dias: 1 },
    { nombre: "Pan omega 3", dias: 1 },
    { nombre: "Pastel nata (Pastel Belem)", dias: 1 },
    { nombre: "Placa hojaldre mantequilla", dias: 1 },
    { nombre: "Roll de canela", dias: 1 },
    { nombre: "Rollito cacao petit dore", dias: 1 },
    { nombre: "Salsa holandesa (preparado)", dias: 1 },
    { nombre: "Sandwich brioche trufado", dias: 1 },
    { nombre: "Sandwich salmon club", dias: 1 },
    { nombre: "Sandwich Santagloria club", dias: 1 },
    { nombre: "Santa", dias: 2 },
    { nombre: "Santa chocolate", dias: 2 },
    { nombre: "Santa chocolate blanco", dias: 2 },
    { nombre: "Tomate triturado", dias: 2 },
    { nombre: "Tortitas choco avellanas", dias: 1 },
    { nombre: "Tortitas frutos rojos", dias: 1 },
    { nombre: "Trenza Almudévar", dias: 4 },
    { nombre: "Vinagreta pesto", dias: 2 }
  ],

  "Secos": [
    { nombre: "Aceite de oliva virgen 3x5lt", dias: 60 },
    { nombre: "Almendra granillo", dias: 0 },
    { nombre: "Avellana tostada", dias: 0 },
    { nombre: "Azúcar glass saco 10kg", dias: 0 },
    { nombre: "Azúcar", dias: 0 },
    { nombre: "Café eco nat descafeinado", dias: 5 },
    { nombre: "Café eco nat SG 8x1kg", dias: 5 },
    { nombre: "Canela molida", dias: 0 },
    { nombre: "Caramelos violetas", dias: 0 },
    { nombre: "Cebolla frita deshidratada", dias: 15 },
    { nombre: "Choco crispies", dias: 0 },
    { nombre: "Cobertura blanca choco 10kg", dias: 0 },
    { nombre: "Cobertura vegetal choco", dias: 0 },
    { nombre: "Coco rallado", dias: 0 },
    { nombre: "Crema pastelera saco", dias: 0 },
    { nombre: "Crema pistacho", dias: 0 },
    { nombre: "Frappé vainilla", dias: 0 },
    { nombre: "Galleta filipinos", dias: 15 },
    { nombre: "Galleta molida lotus", dias: 15 },
    { nombre: "Galleta molida oreo", dias: 15 },
    { nombre: "Gelatina miroir cubo", dias: 0 },
    { nombre: "Glasseado (cinamon roll)", dias: 20 },
    { nombre: "Granos de chía", dias: 0 },
    { nombre: "Mermelada frutos bosque", dias: 0 },
    { nombre: "Miel de flores", dias: 365 },
    { nombre: "Nocciolata", dias: 0 },
    { nombre: "Nocilla fluida", dias: 0 },
    { nombre: "Nueces cuartos", dias: 30 },
    { nombre: "Orégano seco", dias: 0 },
    { nombre: "Pipas de calabaza", dias: 0 },
    { nombre: "Pistacho granillo", dias: 0 },
    { nombre: "Semilla sésamo", dias: 0 },
    { nombre: "Sirope azúcar caña", dias: 0 },
    { nombre: "Sirope chocolate Colac", dias: 0 },
    { nombre: "Sirope coco", dias: 0 },
    { nombre: "Sirope galleta negra", dias: 0 },
    { nombre: "Sirope lotus", dias: 60 },
    { nombre: "Sirope tiramisú", dias: 0 },
    { nombre: "Sirope vainilla", dias: 0 },
    { nombre: "Sirope violeta", dias: 60 }
  ]
};

const obradorData = {
    "productos": [
        {
            "nombre": "Crujiente de Manzana",
            "descongelacion": "3 min a temperatura ambiente",
            "horno_temp": "170°C",
            "horno_prog": "3",
            "horno_tiempo": "35 min",
            "ingredientes": "Hojaldre, manzana, azúcar, gelatina",
            "preparacion": "Rebozar la base de hojaldre con 2gr de azúcar. Añadir 210gr de crema pastelera en toda la base. Hornear a 170°C durante 35 minutos. Pintar con 2gr de gelatina espejo."
        },
        {
            "nombre": "Banda de Hojaldre con Frutas",
            "descongelacion": "No se especifica",
            "horno_temp": "170°C",
            "horno_prog": "3",
            "horno_tiempo": "35 min",
            "ingredientes": "Hojaldre, frutas, crema pastelera, azúcar",
            "preparacion": "Hornear a 170°C durante 35 min. No necesita vapor. Debe quedar con un color dorado."
        },
        {
            "nombre": "Pastel Belem Caprice",
            "descongelacion": "45 min a temperatura ambiente",
            "horno_temp": "250°C",
            "horno_prog": "N/A",
            "horno_tiempo": "8 a 10 min",
            "ingredientes": "Hojaldre, crema pastelera",
            "preparacion": "Hornear a 250°C de 8 a 10 min. Debe quedar dorado. Servir caliente."
        },
        {
            "nombre": "Brownie",
            "descongelacion": "Descongelar sobre bandeja",
            "horno_temp": "N/A",
            "horno_prog": "N/A",
            "horno_tiempo": "N/A",
            "ingredientes": "Brownie, azúcar",
            "preparacion": "Descongelar en bandeja. Se puede calentar si se desea en el microondas."
        },
        {
            "nombre": "Tortitas Frutos Rojos",
            "descongelacion": "1 hora a temperatura ambiente",
            "horno_temp": "200°C",
            "horno_prog": "7",
            "horno_tiempo": "2 min",
            "ingredientes": "Tortitas, mermelada de frutos rojos",
            "preparacion": "Descongelar 1 hora a temperatura ambiente. Calentar en el Merrychef. En un plato poner a un lado 1 fortita y repartir en zigzag 60gr de mermelada dejando caer por los bordes. Añadir otra tortita y repetir. Añadir la tercera y terminar con la."
        },
        {
            "nombre": "Croissant de Mantequilla",
            "descongelacion": "No se especifica",
            "horno_temp": "185°C",
            "horno_prog": "1",
            "horno_tiempo": "18 min",
            "ingredientes": "No se especifica",
            "preparacion": "Hornear a 185°C durante 18 min."
        },
        {
            "nombre": "Gloria Básica",
            "descongelacion": "Descongelar congelado en bandeja",
            "horno_temp": "185°C",
            "horno_prog": "1",
            "horno_tiempo": "15 min",
            "ingredientes": "No se especifica",
            "preparacion": "Hornear a 185°C, programa 1, durante 15 minutos."
        },
        {
            "nombre": "Focaccia",
            "descongelacion": "No se especifica",
            "horno_temp": "200°C",
            "horno_prog": "2",
            "horno_tiempo": "8 min",
            "ingredientes": "No se especifica",
            "preparacion": "Hornear a 200°C, programa 2, durante 8 minutos."
        },
        {
            "nombre": "Ensalada Pollo Cesar",
            "descongelacion": "N/A",
            "horno_temp": "N/A",
            "horno_prog": "N/A",
            "horno_tiempo": "N/A",
            "ingredientes": "Ensalada campestre, espinaca, rúcula, pollo asado deshebrado, grana padano, tomatitos cherry, cebolla frita, orégano, chusco",
            "preparacion": "Repartir 40gr de ensalada, 15gr de espinaca y 5gr de rúcula. Añadir 50gr de pollo asado y 20gr de grana padano. Distribuir 40gr de tomatitos, 5gr de cebolla frita y 0.5gr de orégano. Servir con pan chusco aparte."
        },
        {
            "nombre": "Ensalada Italiana",
            "descongelacion": "N/A",
            "horno_temp": "N/A",
            "horno_prog": "N/A",
            "horno_tiempo": "N/A",
            "ingredientes": "Espinaca, rúcula, pasta, tomate seco",
            "preparacion": "Repartir 15gr de espinaca y 5gr de rúcula. Añadir 160gr de pasta con un poco de AOVE. Distribuir 10gr de tomate seco cortado en juliana."
        }
    ]
};
